import { Josefin_Sans, Inter } from "next/font/google";
import localFont from "next/font/local";
import { Analytics } from '@vercel/analytics/next';

import "./globals.css";

// If loading a variable font, you don't need to specify the font weight
const josefinSans = Josefin_Sans({
  weight: "300",
  subsets: ["latin"],
  variable: "--font-josefinSans",
});

const inter = Inter({
  weight: "300",
  subsets: ["latin"],
  variable: "--font-inter",
});

// Font files can be colocated inside of `app`
const fonsecaMedium = localFont({
  src: "./fonseca/Fonseca-Medium.otf",
  display: "swap",
  variable: "--font-fonseca-medium",
});

const fonsecaLight = localFont({
  src: "./fonseca/Fonseca-Light.otf",
  display: "swap",
  variable: "--font-fonseca-light",
});

const fonsecaThin = localFont({
  src: "./fonseca/Fonseca-Thin.otf",
  display: "swap",
  variable: "--font-fonseca-thin",
});

export const metadata = {
  title: "Roy Armale",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${josefinSans.variable} ${inter.variable} ${fonsecaMedium.variable} ${fonsecaLight.variable} ${fonsecaThin.variable}`}
      >
        {children}
        <Analytics />
      </body>
    </html>
  );
}
